apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{APP_NAME}}
spec:
  backendType: secretsManager
  # optional: specify region
  region: {{AWS_REGION}}
  dataFrom:
    - {{APP_NAME}}/credentials