apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{PORT}}
      targetPort: {{PORT}}
  selector:
    app: {{APP_NAME}}