---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{HOST_DNS}}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{APP_NAME}}
            port:
              number: {{PORT}}